### ISSUE TITLE
shutdown doesn't work

### ISSUE THREAD

**Issue by ezequielabregu** [BenjaminStonawski/Hackintosh-for-Lenovo-G580#2]
Hi
congrats for your work. I have almost fully (99%) laptop hackintosh thanks to your help. 
Have you had any problem when you shutdown Catalina (10.15.5)? In my case, My Lenovo g580 just crash, then reboot and when Catalina starts (without problem) I can see the problem. 
Regards.

**Comment by BenjaminStonawski** [comment]
Hello there!
Thank you for using my repo!
Well, I never have tried macOS 10.15.5 on G580, I will check it and gonna try to fix it. 
Gonna tell you about this if I can tell anything new updates.
Best regards,
Benjamin Stonawski

**Comment by ezequielabregu** [comment]
Hi! I fixed my problem. Basically, I deleted ALXEthernet.kext (a kext that I needed to use my ethernet internal interface, not included in your repo!), and replaced with AtherosE2200Ethernet.kext. 

ALXEthernet produce dramatic crashes whit shutdown and restart functions.

Everything works. I have made some extra tweaks but now Catalina 10.15.5 is working like a charm on my Lenovo g580. Thanks again!

**Comment by BenjaminStonawski** [comment]
Wow! Really nice to hear that :D 
If you could add a pull request to add AtherosE2200Ethernet.kext to the Clover config that would be cool!
And again, thank you for using my config and I'm happy to see that your Hackintosh is working fine :D 
Have a nice day,
Benjamin Stonawski

**Comment by of-ravens-claw** [comment]
Closed #2 as the problem has been fixed.
