### ISSUE TITLE
Changes required for G580 i5 Intel HD 4000

### ISSUE THREAD

**Issue by aswinmohanme** [BenjaminStonawski/Hackintosh-for-Lenovo-G580#4]
I have successfully booted on my machine, but Graphics and Ethernet does not work. 

How do I make the necessary changes, on your working config ?

**Comment by aswinmohanme** [comment]
I have successfully installed macOS on the above said configuration. 

* Ethernet works with AtherosKext
* Display works with Injecting Intel and setting correct id

[Updated Clover Files](https://github.com/BenjaminStonawski/Hackintosh-for-Lenovo-G580/files/5005732/CLOVER.zip)

**Comment by of-ravens-claw** [comment]
> 
> 
> I have successfully installed macOS on the above said configuration.
> 
>     * Ethernet works with AtherosKext
> 
>     * Display works with Injecting Intel and setting correct id
> 
> 
> [Updated Clover Files](https://github.com/BenjaminStonawski/Hackintosh-for-Lenovo-G580/files/5005732/CLOVER.zip)

Hello, the reason for this is quite simple, the Intel HD4000 is a different GPU, Ivy bridge one to be exact, I haven't looked at your changes, but since it works, thats cool.

Closed #4.

**Comment by vijayrajesh** [comment]
@aswinmohanme Thanks for your Clover file.  It helped me too.  BTW, May I know how to enable brightness slider natively ?  Do you have the brightness slider?

**Comment by aswinmohanme** [comment]
I haven't tried making it work. I have switched away in the meantime.

**Comment by vijayrajesh** [comment]
ok no problem, Thanks for the reply.
